version: '3.8'

services:
  counterfactual-lab-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: counterfactual-lab-dev
    ports:
      - "8501:8501"  # Streamlit
      - "8080:8080"  # Metrics
      - "5678:5678"  # Debugger
    volumes:
      - .:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - COUNTERFACTUAL_LAB_ENV=development
      - COUNTERFACTUAL_LAB_DEBUG=true
      - PYTHONPATH=/app/src
      - CUDA_VISIBLE_DEVICES=0
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: /bin/bash
    profiles:
      - dev

  redis:
    image: redis:7-alpine
    container_name: counterfactual-lab-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    profiles:
      - dev
      - full

  postgres:
    image: postgres:15-alpine
    container_name: counterfactual-lab-postgres
    environment:
      POSTGRES_DB: counterfactual_lab
      POSTGRES_USER: counterfactual_lab
      POSTGRES_PASSWORD: counterfactual_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - dev
      - full

  prometheus:
    image: prom/prometheus:latest
    container_name: counterfactual-lab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring
      - full

  grafana:
    image: grafana/grafana:latest
    container_name: counterfactual-lab-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    profiles:
      - monitoring
      - full

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: counterfactual-lab-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ~/.cache/huggingface:/home/jovyan/.cache/huggingface
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/work/src
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    profiles:
      - jupyter
      - full

volumes:
  redis-data:
  postgres-data:
  prometheus-data:
  grafana-data: