version: '3.8'

services:
  counterfactual-lab:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/home/app/data:ro
      - ./outputs:/home/app/outputs
    networks:
      - counterfactual-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  counterfactual-lab-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8501:8501"
      - "8888:8888"  # Jupyter
    environment:
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
    volumes:
      - .:/home/app/workspace
      - ./data:/home/app/data
      - ./outputs:/home/app/outputs
    networks:
      - counterfactual-net
    command: >
      bash -c "
        pip install jupyter &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "
    profiles:
      - dev

networks:
  counterfactual-net:
    driver: bridge

volumes:
  data:
  outputs: