blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/danieleschmidt/multimodal-counterfactual-lab/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://counterfactual-lab.readthedocs.io
    about: Check the documentation for guides and API reference
  - name: 🔧 Support
    url: https://discord.gg/counterfactual-lab
    about: Get help from the community on Discord