version: '3.8'

# Production deployment configuration for Multimodal Counterfactual Lab
# This extends the base docker-compose.yml for production use

services:
  counterfactual-lab-prod:
    image: counterfactual-lab:latest
    restart: unless-stopped
    ports:
      - "80:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/home/app/data:ro
      - ./outputs:/home/app/outputs
      - ./logs:/home/app/logs
    networks:
      - counterfactual-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - counterfactual-lab-prod
    networks:
      - counterfactual-prod

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - counterfactual-prod
    deploy:
      resources:
        limits:
          memory: 512M

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - counterfactual-prod
    profiles:
      - monitoring

  # Grafana for visualization (optional)
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - counterfactual-prod
    profiles:
      - monitoring

networks:
  counterfactual-prod:
    driver: bridge

volumes:
  redis_data:
  prometheus_data:
  grafana_data: