name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install pip-tools
        run: |
          pip install pip-tools
          pip install -e ".[dev]"
      
      - name: Generate lock files
        run: |
          pip-compile pyproject.toml --output-file requirements.txt
          pip-compile pyproject.toml --extra dev --output-file requirements-dev.txt
          pip-compile pyproject.toml --extra test --output-file requirements-test.txt
          pip-compile pyproject.toml --extra security --output-file requirements-security.txt
      
      - name: Install updated dependencies
        run: |
          pip install -r requirements-dev.txt
      
      - name: Run tests
        run: |
          make test-fast
          make security-scan
      
      - name: Check if there are changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'deps: update dependencies to latest versions'
          title: 'Automated dependency updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates generated by the dependency-update workflow.
            
            ### 📦 Changes Made
            - Updated Python dependencies to latest compatible versions
            - Generated fresh lock files for reproducible builds
            - Ran security scans to ensure no vulnerabilities
            - Verified tests pass with updated dependencies
            
            ### ✅ Validation
            - [x] All tests pass
            - [x] Security scans completed
            - [x] Lock files generated
            - [x] No breaking changes detected
            
            ### 🔍 Review Checklist
            - [ ] Review dependency changes for breaking changes
            - [ ] Verify all tests pass in CI
            - [ ] Check for any new security vulnerabilities  
            - [ ] Ensure performance is not degraded
            - [ ] Validate compatibility with ML model dependencies
            
            ### 🤖 Automation Details
            - **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
            - **Workflow**: dependency-update.yml
            - **Python Version**: 3.11
            - **Test Suite**: Fast tests + Security scan
            
            ---
            🤖 *This PR was created automatically by Terragon Autonomous SDLC*
          branch: automated/dependency-updates
          labels: |
            dependencies
            automated
            terragon
          reviewers: |
            danieleschmidt
          assignees: |
            danieleschmidt