apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    version: 1
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      defaultRegion: us-east-1
      customQueryParameters: ""
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}