name: Autonomous SDLC Monitoring

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      force_discovery:
        description: 'Force value discovery run'
        required: false
        default: 'false'
        type: boolean

jobs:
  autonomous-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for git analysis
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,security]"
        sudo apt-get update
        sudo apt-get install -y bc  # For calculations in monitoring script
    
    - name: Run Security Scan
      run: |
        # Run security scans to generate reports for monitoring
        bandit -r src/ --severity-level medium --confidence-level medium --format json -o bandit-report.json || true
        safety check --json --output safety-report.json --ignore 70612 || true
      continue-on-error: true
    
    - name: Run Autonomous SDLC Monitor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FORCE_DISCOVERY: ${{ github.event.inputs.force_discovery }}
      run: |
        # Run the autonomous monitoring script
        ./.terragon/autonomous-monitor.sh
    
    - name: Upload Monitoring Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: autonomous-sdlc-reports
        path: |
          .terragon/monitor.log
          .terragon/value-metrics.json
          BACKLOG.md
          bandit-report.json
          safety-report.json
        retention-days: 30
    
    - name: Update Repository Status
      if: always()
      run: |
        # Update repository status in README or create status badge
        echo "Last autonomous check: $(date -u)" >> .terragon/last-check.txt
    
    - name: Create Issue for Critical Items
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          try {
            // Read value metrics to find critical items
            const metricsData = fs.readFileSync('.terragon/value-metrics.json', 'utf8');
            const metrics = JSON.parse(metricsData);
            
            const criticalItems = metrics.discoveredItems?.filter(item => 
              item.priority === 'critical' && item.scores?.composite > 80
            ) || [];
            
            if (criticalItems.length > 0) {
              const issueBody = `## 🚨 Critical Value Items Discovered
              
              The Terragon Autonomous SDLC system has discovered ${criticalItems.length} critical value items that require immediate attention:
              
              ${criticalItems.map((item, i) => `
              ### ${i + 1}. ${item.title}
              - **Score**: ${item.scores?.composite || 0} (Critical threshold: 80+)
              - **Category**: ${item.category}
              - **Estimated Effort**: ${item.effort || 'Unknown'} hours
              - **Source**: ${item.source}
              `).join('\n')}
              
              ## 🎯 Recommended Actions
              
              1. Review the [BACKLOG.md](./BACKLOG.md) for complete prioritization
              2. Address the highest-scoring items first
              3. Consider creating dedicated PRs for each critical item
              
              ## 📊 Repository Health
              - **Current Maturity**: ${metrics.repository?.currentScore || 'Unknown'}%
              - **Last Discovery**: ${metrics.continuousMetrics?.lastDiscoveryRun || 'Unknown'}
              
              ---
              🤖 *Automatically generated by Terragon Autonomous SDLC*
              `;
              
              // Check if similar issue exists
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'autonomous-sdlc,critical'
              });
              
              if (issues.length === 0) {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: `🚨 Critical SDLC Items Discovered (${criticalItems.length} items)`,
                  body: issueBody,
                  labels: ['autonomous-sdlc', 'critical', 'terragon']
                });
                
                console.log(`Created issue for ${criticalItems.length} critical items`);
              } else {
                console.log('Critical issue already exists, skipping creation');
              }
            } else {
              console.log('No critical items found');
            }
          } catch (error) {
            console.error('Error processing critical items:', error);
          }

  value-discovery:
    runs-on: ubuntu-latest
    if: github.event.inputs.force_discovery == 'true' || github.event_name == 'schedule'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run Value Discovery
      run: |
        echo "🔍 Running forced value discovery..."
        python .terragon/discover-value.py
    
    - name: Create Pull Request with Updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update value discovery metrics and backlog'
        title: '🤖 Autonomous Value Discovery Update'
        body: |
          ## 🤖 Autonomous Value Discovery Update
          
          This PR contains updates from the autonomous value discovery system.
          
          ### 📊 Changes Made
          - Updated value metrics in `.terragon/value-metrics.json`
          - Refreshed prioritized backlog in `BACKLOG.md`
          - Discovered new value opportunities
          
          ### 🎯 Key Discoveries
          See `BACKLOG.md` for the latest prioritized value items and recommendations.
          
          ### 🔄 Next Steps
          - Review the updated backlog
          - Consider implementing the highest-value items
          - Merge this PR to keep metrics current
          
          ---
          🤖 *Generated by Terragon Autonomous SDLC Agent*
        branch: autonomous/value-discovery-update
        labels: |
          autonomous-sdlc
          value-discovery
          terragon
        delete-branch: true